services:
  # Serviço principal da API
  - type: web
    name: arboviroses-backend-final
    env: python
    pythonVersion: 3.12.4
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn src.main:app"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: arboviroses-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production

  # Job de coleta de dados climáticos (diário às 06:00 UTC)
  - type: cron
    name: climate-collector-job
    env: python
    pythonVersion: 3.12.4
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python src/jobs/run_climate_job.py"
    schedule: "0 6 * * *"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: arboviroses-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true

  # Job de coleta de dados InfoDengue (diário às 07:00 UTC)
  - type: cron
    name: infodengue-collector-job
    env: python
    pythonVersion: 3.12.4
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python src/jobs/run_infodengue_job.py"
    schedule: "0 7 * * *"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: arboviroses-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true

  # Job de coleta histórica (semanal às segundas 05:00 UTC)
  - type: cron
    name: historical-collector-job
    env: python
    pythonVersion: 3.12.4
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python src/jobs/run_historical_job.py"
    schedule: "0 5 * * 1"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: arboviroses-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true

  # Job de predição mensal (primeiro dia do mês às 08:00 UTC)
  - type: cron
    name: monthly-prediction-job
    env: python
    pythonVersion: 3.12.4
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python -c 'from src.jobs.scheduler import JobScheduler; JobScheduler().monthly_prediction_job()'"
    schedule: "0 8 1 * *"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: arboviroses-db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true

databases:
  - name: arboviroses-db
    databaseName: arboviroses
    user: arboviroses_user
